apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: exigir-nonroot
  annotations:
    policies.kyverno.io/title: Exigir runAsNonRoot
    policies.kyverno.io/severity: medium
spec:
  validationFailureAction: Enforce
  background: true
  rules:
    - name: precisa-runasnonroot
      match:
        any:
          - resources:
              kinds: ["Pod"]
      validate:
        message: "Pods devem definir securityContext.runAsNonRoot: true."
        pattern:
          spec:
            =(securityContext):
              =(runAsNonRoot): "true"
            containers:
              - =(securityContext):
                  =(runAsNonRoot): "true"
